# Skaffold configuration for local development of multi-client.
apiVersion: skaffold/v2beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: joustava/multi-client
      context: client
      docker:
        dockerfile: "Dockerfile.dev"
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
          - '**/*.html'
            
    - image: joustava/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: 
          - '**/*.js'
    - image: joustava/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml